@HostAddress = http://localhost:5181/graphql

### Ok - CreateEmployee

POST {{HostAddress}}
Content-Type: application/json
Accept: application/graphql-response+json; charset=utf-8

{ 
  "query": "mutation { createEmployee(employee: { name: \"george\", lastname: \"baxter\" }) { id } }" 
}
