@HostAddress = http://localhost:5181/graphql

### Ok - nameless query

POST {{HostAddress}}
Content-Type: application/json
Accept: application/graphql-response+json; charset=utf-8

{
  "query": "query { greeting }"
}

### Ok - query with name

POST {{HostAddress}}
Content-Type: application/json
Accept: application/graphql-response+json; charset=utf-8

{
  "query": "query GetGreeting { greeting }"
}

### Ok - query employees

POST {{HostAddress}}
Content-Type: application/json
Accept: application/graphql-response+json; charset=utf-8

{
  "query": "query { employees { name, lastname} }"
}